### ISSUE TITLE
Migration to version 10.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/crm#117]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0
# Modules to migrate
- [ ] crm_action - ~~By @qtheuret - #147~~ By @dsidorenkovas-rg - #211 
- [x] crm_claim - From Odoo core in 9.0 - By @cubells - #170
- [x] crm_claim_code - By @cubells - #171 
- [x] crm_claim_type - By @bodedra - #180 
- [x] crm_deduplicate_acl - By @luismontalba - #152 
- [x] crm_deduplicate_filter - By @luismontalba - #159 
- [ ] crm_lead_address_street3
- [x] crm_lead_code - By @nicolasramos - #156 
- [x] ~~crm_lead_lost_reason - Included in core~~
- [ ] crm_lead_sale_link
- [ ] crm_lead_stage_monitoring
- [x] crm_lead_website - By @chienandalu - #151 
- [x] crm_location - By @luismontalba - #157 
- [x] crm_phonecall - By @cubells - #138 
- [x] crm_phonecall_summary_predefined - By @cubells - #144 
- [x] crm_sale_marketing - By @mreficent - #164 
- [x] crm_sector - By @luismontalba - #153 
- [ ] crm_track_next_action
- [ ] lettermgmt
- [ ] lettermgmt_hr
- [x] marketing_crm_partner - By @chienandalu - #175 
- [ ] mass_mailing_partner
- [ ] newsletter
- [ ] partner_withdrawal

**Comment by ruifranco** [comment]
I've been testing the refactored v8's version of "letter management" in v10 and everything seems alright providing the creation of "ir.sequence.type" records in "data/letter_sequence.xml" is removed.

**Comment by bimajatiwijaya** [comment]
Hi @pedrobaeza ,
I need your advice. I see on odoo10.0 module crm_claim was not exist.
How to migrate module which depend to crm_claim ?

**Comment by pedrobaeza** [comment]
@bimajatiwijaya, there are 3 possible ways:

* Include a migration from Odoo's crm_claim module here in the repository.
* Merge needed objects from crm_claim repository in the main module crm_claim_rma and don't depend on it.
* Refactor crm_claim_rma to another thing not depending anymore on crm_claim, and maybe just call it `rma`.

**Comment by bimajatiwijaya** [comment]
Ok thank you @pedrobaeza .

**Comment by bodedra** [comment]
@pedrobaeza @max3903 

Would you please remove my name from *crm_claim_code* module 

PR: #171

**Comment by bodedra** [comment]
PR #180 for crm_claim_type.

**Comment by cubells** [comment]
@bodedra 

From copyright header?

**Comment by bodedra** [comment]
@cubells 

I meant with above "Modules to Migration" list.

**Comment by cubells** [comment]
Ok, sorry. @bodedra

**Comment by pedrobaeza** [comment]
Main comment updated. FYI, we have rescued and migrate Odoo's crm_claim module.

**Comment by geluboros** [comment]
Hi @pedrobaeza ,

Since the crm_action PR was not continued, we created a new PR #211, migrating directly from the updated module in v9 to include all functionality.

Could you update the migration list ?

Thanks.

**Comment by pedrobaeza** [comment]
@gboros-rgbconsulting main comment updated, thanks.

**Comment by tbermudezstm** [comment]
This is the error that the server show to me in the migration process from the version 8 to the 10 version of the crm_claim module.

Lot of thanks, regards.

ProgrammingError: relation "crm_team_claim_stage_rel" does not exist
LINE 1: ..."crm_claim_stage"."id" in (SELECT "stage_id" FROM "crm_team_...

**Comment by bodedra** [comment]
@tbermudezstm IMHO please create [new issue](https://github.com/OCA/crm/issues/new) with necessary details and steps.
