### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/crm#179]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [ ] calendar_resource - By @eilst - #224
- [ ] crm_action
- [x] crm_claim - By @oihane - #184 
- [x] crm_claim_code - ~~By @pragyachhabra - #194~~ - By @pedrobaeza - #227 
- [ ] crm_claim_type - By @larmar - #193 
- [x] crm_deduplicate_acl - By @pedrobaeza - #187 
- [x] crm_deduplicate_by_ref - By @chienandalu - #230 
- [x] crm_deduplicate_by_website - By @cristinamartinrod - #233
- [x] crm_deduplicate_filter - By @ernestotejeda - #198 
- [ ] crm_lead_address_street3
- [ ] crm_lead_code
- [x] crm_lead_firstname - By @EmailsGmails - #217 
- [ ] crm_lead_sale_link
- [ ] crm_lead_stage_monitoring
- [x] ~~crm_lead_website~~ - Already included in core
- [ ] crm_location - By @hprasetyou - #201
- [x] crm_meeting_commercial_partner - By @lreficent - #239
- [x] crm_phonecall - By @chienandalu - #212 
- [x] crm_phonecall_planner - By @chienandalu - #213
- [x] crm_phonecall_summary_predefined - By @cristinamartinrod - #223 
- [x] crm_sale_marketing - By @mreficent - #222 
- [x] crm_sector > crm_industry - By @mreficent - #221
- [ ] crm_track_next_action
- [ ] lettermgmt
- [ ] lettermgmt_hr
- [x] marketing_crm_partner - By @cristinamartinrod - #234 
- [ ] newsletter
- [ ] partner_withdrawal

**Comment by emagdalenaC2i** [comment]
Please add to the list crm_deduplicate_by_website that is already merged - By @cristinamartinrod - #233 
crm_sector is renamed as crm_industry and already merged - By @mreficent - #221 
Please add to the list crm_meeting_commercial_partner that is already merged - By @lreficent - #239 
There is a PR for the migration of calendar_resource - By @eilst - #224 
There is a PR for the migration of crm_location - By @hprasetyou - #201
