### ISSUE TITLE
[RFC] Discusion about HelpDesk RoadMap

### ISSUE THREAD

**Issue by DarioLodeiros** [OCA/crm#229]
I will put here some features or changes about #225 to improve the HelpDesk:

- [ ] Make helpdesk independent of CRM. As in the Enterprise edition, I think that the help desk is a new area on its own. (We can connect this with crm or project throught other optional modules)

- [ ] Expand views for ticket management (Add Dashboard, kanban and pivot views for support teams)

- [ ] Add mail alias feature for ticket creation

- [ ] New module to connect Projects and Helpdesk Management

- [ ] Create mail templates and workflow for ticket - customer notifications

- [ ] New module to Portal tickets management.

**Comment by DarioLodeiros** [comment]
About the first proposal (helpdesk indenpendent of CRM): I think that is important take this decision before continuing. Why we need use things like[ lost oportunity reason](https://github.com/OCA/crm/pull/225/files#diff-1a79fdb8cc5d474742aa102e8dfb16fdR57) on a ticket? I do not think it is necessary for a company to have a commercial department to have support equipment ...?

**Comment by pedrobaeza** [comment]
> New module to Website portal tickets management.

In v11 portal is included in core `web` module, so no need for an extra module depending on website.

**Comment by MiquelRForgeFlow** [comment]
> Make helpdesk independent of CRM

I would do that for v12 with a proper rename of the module.

**Comment by DarioLodeiros** [comment]
@mreficent Ok!, I really prefer a independt module, but if you think that is best make it on v12... grrr xD but ok! ;P
@pedrobaeza , but we need make the ticket cursomer logic in the portal... I changed the description :)

**Comment by JordiBForgeFlow** [comment]
@mreficent there's no point to mwrge crm_helpdesk in v11, v10 and v9 if we are considering a new model.

In what version do you need it? 

Are you coming to OCA Days? Perhaps it would be a good place to discuss

It is more important to build into the right model than to try to stick to something that exists today but is not as good. Because you can always migeate into the new model if needed.

**Comment by JordiBForgeFlow** [comment]
Dario, are you comkng to OCA Days?

**Comment by DarioLodeiros** [comment]
No... I cant :(
Anyway... The change is only change the menu item (site it in main menu) and break the crm teams relations (replace them with a own supporr team model...) I think that is a little but important change.
