### ISSUE TITLE
Migration to version 9.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/crm#58]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0
# Modules to migrate
- [ ] crm_action - By @atularvind - #119 
- [x] crm_claim_code - By @cyrillgdn - #90
- [ ] crm_claim_merge here - By @mdietrichc2c - #93
- [x] crm_claim_type - By @cyrilgdn - #92
- [x] crm_deduplicate_acl - By @cubells - #122
- [x] crm_deduplicate_by_website - By @cubells - #127 
- [x] crm_deduplcate_filter - By @cubells - #126 
- [ ] crm_lead_code - By @atularvind - #120 
- [ ] crm_lead_firstname
- [x] ~~crm_lead_lost_reason - Included in core~~
- [ ] crm_lead_stage_monitoring
- [ ] crm_location
- [ ] crm_phonecall_summary_predefined - By @cubells - #132 
- [ ] crm_track_next_action
- [ ] crm_lead_address_street3
- [ ] crm_lead_sale_link
- [ ] lettermgmt - By @HardikG - #115 
- [ ] lettermgmt_hr
- [x] marketing_crm_partner - By @cubells - #123 
- [ ] mass_mailing_partner
- [ ] newsletter
- [ ] partner_withdrawal

**Comment by mmalorni** [comment]
There seems to be a lot less modules in the V9 than in the V8. Is there a reason some modules are not displayed in the readme.md file? Are some modules not at all compatible with the V9. (like the phone call modules since they were removed from community and available only in the enterprise version).  Would it  be a good place to put the old v8 Phone Log and upgrade it to v9 community?

**Comment by pedrobaeza** [comment]
This is because the modules were added after the creation of the 9.0 branch. You can include them without problem following the procedure: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0

**Comment by cyrilgdn** [comment]
crm_claim_type: https://github.com/OCA/crm/pull/92

**Comment by mdietrichc2c** [comment]
Ported 7.0 module `crm_claim_merge` here: https://github.com/OCA/crm/pull/93
